###############################################################################
#
# An inventory to use to set up a machine on EC2 or other cloud provider.
# To use this add the following into your /etc/hosts file:
#
# 12.12.12.12	ala-demo	ala-demo.org 
#
# You'll need to replace "12.12.12.12" with the IP address of your newly created
# Ubuntu 14 instance.
#
# ansible-playbook --private-key ~/.ssh/MyPrivateKey.pem -u ubuntu -s -i ansible/inventories/demo-ec2 ansible/ala-demo.yml
#
###############################################################################

[sndb]
sndb

[sndb:vars]
# Mounted storage is usually /mnt on EC2. Create a symlink to /mnt -> /data
data_dir=/data

demo_hostname = datos.sndb.mincyt.gob.ar

####################### Biocache ##############################################

biocache_db_host = localhost
cassandra_listen_host = localhost
biocache_service_hostname = datos.sndb.mincyt.gob.ar

biocache_service_url = http://datos.sndb.mincyt.gob.ar/biocache-service
biocache_service_base_url = http://datos.sndb.mincyt.gob.ar
biocache_service_context_path = /biocache-service
logging_enabled=true
default_country=
local_node_ip=127.0.0.1

####################### Hub ###################################################

biocache_hub_hostname = datos.sndb.mincyt.gob.ar
biocache_hub_url = http://datos.sndb.mincyt.gob.ar/generic-hub
biocache_hub_base_url = http://datos.sndb.mincyt.gob.ar
biocache_hub_context_path = /generic-hub
userdetails_url=https://datos.sndb.mincyt.gob.ar/userdetails/userDetails

org_url=http://www.mincyt.gob.ar

orgNameLong=SNDB
orgNameShort=sndb

explore_your_area_lat = 54.00366
explore_your_area_lng = -2.547855
explore_your_area_location=Buenos Aires

map_default_latitude = 54.00366
map_default_longitude = -2.547855
map_default_zoom = 5

skin_layout = generic

####################### Collectory ############################################

collectory_hostname = datos.sndb.mincyt.gob.ar
collectory_url = http://datos.sndb.mincyt.gob.ar/collectory
collectory_base_url = http://datos.sndb.mincyt.gob.ar
collectory_context_path = /collectory
collectory_db_host_address = localhost
collectory_db_host = localhost
collectory_db_user = collectory
collectory_db_password = password

orgNameLong = Portal de Datos del Sistema Nacional de Datos Biológicos
orgNameShort = SNDB

# CAS
uri_filter_pattern = /dummy

# Security bypass
security_bypass = true

# External API access
api_key= to_be_added

# Skinning
skin = generic

# Map config
collections_map_lat = 54.00366
collections_map_lon = -2.547855
collections_map_zoom = 5

# Project name
orgNameShort = Portal del SNDB
orgNameLong = Portal de Datos del Sistema Nacional de Datos Biológicos
region = Argentina

# EML config
eml_delivery_point = Godoy Cruz 2320
eml_city = Buenos Aires
eml_admin_area = Ciudad Autónoma de Buenos Aires
eml_postal_code = 1425
eml_country = Argentina

# Disable UI components
disable_map = true
disable_alerts = true
disable_logger = false

# Whether to check API keys for incoming write requests
api_key_check_enabled = false

# GBIF base URL for webservices
gbifApiUrl=http://api.gbif.org/v1

# Logger URL
logger_webservice_url = http://datos.sndb.mincyt.gob.ar/logger-service/service

####################### SOLR #######################

solr_hostname = datos.sndb.mincyt.gob.ar
solr_url = http://datos.sndb.mincyt.gob.ar/solr
solr_base_url = http://datos.sndb.mincyt.gob.ar
solr_context_path = /solr

sandbox_hostname = datos.sndb.mincyt.gob.ar
sandbox_url = http://datos.sndb.mincyt.gob.ar/sandbox
sandbox_base_url = http://datos.sndb.mincyt.gob.ar
sandbox_context_path = /sandbox

################# Logger Service ############

logger_hostname = datos.sndb.mincyt.gob.ar
logger_url = http://datos.sndb.mincyt.gob.ar/logger-service
logger_base_url = http://datos.sndb.mincyt.gob.ar
logger_context_path = /logger-service
logger_db_name = logger
logger_db_username = logger_user
logger_db_password = logger_user
logger_db_hostname = localhost

############### Auth Server #########
auth_base_url=https://datos.sndb.mincyt.gob.ar
auth_cas_url=https://datos.sndb.mincyt.gob.ar/cas

####### When near the GBIF building (e.g. in Europe) the GBIF nexus will likely be fastest #########
use_gbif_nexus=true

####### Disable SDS checks for the demo
sds_enabled=false
